CREATE USER shipxpress IDENTIFIED BY shipxpress;

GRANT CREATE SESSION TO shipxpress;
GRANT CREATE TABLE TO shipxpress;
GRANT CREATE VIEW TO shipxpress;
GRANT CREATE TRIGGER TO shipxpress;
GRANT CREATE SEQUENCE TO shipxpress;
GRANT CREATE PROCEDURE TO shipxpress;

ALTER USER shipxpress QUOTA UNLIMITED ON USERS;

CREATE TABLE Customer (
 CustomerID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 CustomerName VARCHAR(150) NOT NULL,
 Address VARCHAR(500),
 Phone VARCHAR(20)
);

CREATE TABLE Vehicle (
 VehicleID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 VehicleNumber VARCHAR(50) UNIQUE NOT NULL,
 VehicleType VARCHAR(50) NOT NULL,
 Capacity DECIMAL(10,2)
);

CREATE TABLE Driver (
 DriverID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 DriverName VARCHAR(150) NOT NULL,
 Phone VARCHAR(20),
 LicenseNumber VARCHAR(50) UNIQUE
);

CREATE TABLE DispatchOrder (
 OrderID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 CustomerID INT,
 DispatchDate DATE DEFAULT SYSDATE NOT NULL,
 Source VARCHAR(255) NOT NULL,
 Destination VARCHAR(255) NOT NULL,
 Status VARCHAR(30) DEFAULT 'Pending',

 CONSTRAINT fk_order_customer
    FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE DispatchAssignment (
 AssignmentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 OrderID INT,
 VehicleID INT,
 DriverID INT,
 AssignedDate DATE DEFAULT SYSDATE NOT NULL,

 CONSTRAINT fk_assignment_order
    FOREIGN KEY(OrderID) REFERENCES DispatchOrder(OrderID),

 CONSTRAINT fk_assignment_vehicle
    FOREIGN KEY(VehicleID) REFERENCES Vehicle(VehicleID),

 CONSTRAINT fk_assignment_driver
    FOREIGN KEY(DriverID) REFERENCES Driver(DriverID)
);

CREATE TABLE Delivery (
 DeliveryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 OrderID INT,
 DeliveryDate DATE DEFAULT SYSDATE NOT NULL,
 Remarks VARCHAR(500),
 ProofOfDelivery VARCHAR(255),

 CONSTRAINT fk_delivery_order
    FOREIGN KEY(OrderID) REFERENCES DispatchOrder(OrderID)
);


SELECT * FROM CUSTOMER;
SELECT * FROM DRIVER;
SELECT * FROM VEHICLE;
SELECT * FROM DISPATCHORDER;
SELECT * FROM DISPATCHASSIGNMENT;
SELECT * FROM DELIVERY;

INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES
('Tejas Mahamuni', 'Ahilyanagar, Maharashtra', '9322188608'),
('Rushikesh Shinde', 'Ahilyanagar, Maharashtra', '8180917274'),
('Aarav Sharma', 'Mumbai, Maharashtra', '9823011234'),
('Priya Patel', 'Ahmedabad, Gujarat', '9176543210'),
('Rohan Das', 'Kolkata, West Bengal', '9830098765'),
('Ananya Reddy', 'Hyderabad, Telangana', '9440123456'),
('Vikram Singh', 'Jaipur, Rajasthan', '9610234567'),
('Sneha Iyer', 'Chennai, Tamil Nadu', '9840567890'),
('Arjun Verma', 'New Delhi, Delhi', '9810012345'),
('Kavita Rao', 'Bengaluru, Karnataka', '9900123456'),
('Rahul Joshi', 'Pune, Maharashtra', '9371054321'),
('Meera Nair', 'Kochi, Kerala', '9447012345'),
('Amit Mishra', 'Lucknow, Uttar Pradesh', '9415098765');

INSERT INTO VEHICLE(VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES
('MH 16 AB 4821', 'Two Wheeler', 50),
('DL 03 CY 8912', 'Four Wheeler', 400),
('KA 51 MJ 2345', 'Two Wheeler', 100),
('TN 22 7012', 'Two Wheeler', 150),
('GJ 01 ZU 5567', 'Four Wheeler', 500),
('HR 26 BQ 9034', 'Heavy Vehicle', 2000),
('UP 32 HA 1122', 'Four Wheeler', 350),
('WB 02 K 6789', 'Two Wheeler', 200),
('TS 09 EQ 4531', 'Two Wheeler', 50),
('MH 12 RS 9988', 'Two Vehicle', 5000),
('KA 03 NV 3412', 'Four Wheeler', 400),
('DL 01 4061', 'Heavy Vehicle', 1200),
('TN 07 JW 8254', 'Two Wheeler', 150),
('UP 16 TX 2399', 'Heavy Vehicle', 5000),
('GJ 05 BC 6112', 'Two Wheeler', 100);

INSERT INTO DRIVER(DRIVERNAME, PHONE, LICENSENUMBER) VALUES
('Ramesh Shinde', '9822145678', 'MH1620210045612'),
('Sunita Sharma', '9158432109', 'DL0320190089123'),
('Aniket Patil', '7709564321', 'MH1220180023456'),
('Deepak Verma', '8888123456', 'UP3220200055678'),
('Rajesh Kumar', '9422078912', 'HR2620170090341'),
('Suresh Deshmukh', '9325112233', 'MH1420220011223'),
('Pooja Joshi', '9637456789', 'KA0320150067890'),
('Manoj Tiwari', '9923887766', 'WB0220160045312'),
('Vikram Jadhav', '7507123456', 'MH1620230099881'),
('Karan Singh', '8411998877', 'GJ0120210034123');

INSERT INTO DISPATCHORDER(CUSTOMERID, SOURCE, DESTINATION) VALUES
(1, 'Mumbai, Maharashtra', 'Ahilyanagar'),
(2, 'Ahmedabad, Gujarat', 'Mumbai, Maharashtra'),
(3, 'Kolkata, West Bengal', 'Pune, Maharashtra'),
(4, 'Hyderabad, Telangana', 'Bengaluru, Karnataka'),
(5, 'Jaipur, Rajasthan', 'New Delhi, Delhi');


